### ISSUE TITLE
Opening Header (.h) File Support

### ISSUE THREAD

**Issue by pcpro178** [sliptrixx/cpp-group#1]
Support is needed for opening a header (.h) file next to its source file.

**Comment by sliptrixx** [comment]
Just for some clarity, are you referring to a `.c` file as a source file? Currently the extension opens a matching `.h` file next to a `.cpp` file. Want to make sure that this behavior is not broken on your end.

**Comment by pcpro178** [comment]
Recognition of .c files would be nice (mixed projects and such), but I created a separate [issue](https://github.com/sliptrixx/cpp-group/issues/2) for that.  What I'm seeing is that the extension only seems to work for opening .cpp files.  If I open a .h file that indeed has a related .cpp file.  The extension fails to position the .h file tab next to its corresponding, already open .cpp file tab.  This is for Visual Studio Code Version: 1.94.1.

**Comment by sliptrixx** [comment]
Okay cool thanks. It's working on my end so let me try to do a bunch of other things to reproduce it.

**Comment by sliptrixx** [comment]
Unfortunately I can't reproduce this on my end :(

**Comment by sliptrixx** [comment]
Unable to reproduce this issue. Closing for now.
![Code_cppgroup1issueUnableToRepro](https://github.com/user-attachments/assets/a1ea86d1-95b7-4574-add3-82416ab5ffe9)
